# This workflow will check pull request and run tests

name: Pull Request Check

on:
  pull_request:
    branches:
      - master

jobs:
  pr-labler:
    permissions:
      contents: read
      pull-requests: write
    name: 🏷️ PR Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0

  build:
    name: 🛂 Pull Request Check
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository ⚙️
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Java 21 ⚙️
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle dependencies cache ⚙️
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.0.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle wrapper cache ⚙️
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.0.3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Validate Gradle wrapper 🔎
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build and test 🏗
        run: ./gradlew test jacocoTestReport sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish Test Results 🚦
        uses: EnricoMi/publish-unit-test-result-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        if: always()
        with:
          files: |
            build/test-results/test/*.xml
